### ISSUE TITLE
Change the annotation string format

### ISSUE THREAD

**Issue by bdtiger** [qsun/ModelAnnotation#7]
The previous annotation string format is 
<pre>
/* MODEL ANNOTATION:
@property int $id Type: int(10) unsigned, Extra: auto_increment, Default: null, Key: PRI
@property string $name Type: varchar(255), Extra: , Default: null, Key: nil
@property string $email Type: varchar(255), Extra: , Default: null, Key: UNI
@property string $password Type: varchar(60), Extra: , Default: null, Key: nil
@property string|null $remember_token Type: varchar(100), Extra: , Default: null, Key: nil
@property int|null $created_at Type: timestamp, Extra: , Default: null, Key: nil
@property int|null $updated_at Type: timestamp, Extra: , Default: null, Key: nil

END MODEL ANNOTATION */
</pre>

It is hard to read. I am proposing a new format. The format is given below. It is easily understandable. 

<pre>
/* MODEL ANNOTATION:
@property	$id                      Type: bigint(20) unsigned      Extra: auto_increment      Default: null      Key: PRI
@property	$name                    Type: varchar(255)             Extra:                     Default: null      Key: nil
@property	$email                   Type: varchar(255)             Extra:                     Default: null      Key: UNI
@property	$email_verified_at       Type: timestamp                Extra:                     Default: null      Key: nil
@property	$password                Type: varchar(255)             Extra:                     Default: null      Key: nil
@property	$remember_token          Type: varchar(100)             Extra:                     Default: null      Key: nil
@property	$created_at              Type: timestamp                Extra:                     Default: null      Key: nil
@property	$updated_at              Type: timestamp                Extra:                     Default: null      Key: nil

END MODEL ANNOTATION */

</pre>

**Comment by qsun** [comment]
Hi @bdtiger 

I think it makes perfect sense, and it indeed looks much better than previous.

**Comment by bdtiger** [comment]
Hi @qsun 
Thanks. I have changed the code to a new branch. But I can not push the code. How can I push the code?

**Comment by qsun** [comment]
Thanks @bdtiger A Pull Request would be nice.

**Comment by qsun** [comment]
Thanks.
